/**
 * @callback onChatStarted
 * Called on the first response from the LLM
 */

/**
 * @callback onChatToken
 * Called for every token generated by the LLM
 * @param {string} token the generated token
 */

/**
 * @callback onChatEnd
 * Called when the LLM has ended the conversation
 */

function nanobotMain() {

    const STYLE = `
:root {
    --chat-height: 20rem;

    --main-color: #3c7c80;
    --accent-color: #ffa00c;
    --white-color: #ffffff;
    --black-color: #000000;
    --dim-color: #e2e2e2;
}

@keyframes loading {
	0% {
		background-position: -100%;
	}
	50% {
		background-position: 0%;
	}
	100% {
		background-position: 100%;
	}
}

.chat-container {
    position: fixed !important;

    overflow: hidden;
    padding: 6px;
    padding-bottom: 0;

    box-sizing: border-box;

    pointer-events: none;

    width: 23rem;
    height: var(--chat-height);

    top: calc(100vh - var(--chat-height));
    right: 1rem;
}

.chat-box {
    display: flex;
    flex-direction: column;

    width: 100%;
    height: 100%;

    pointer-events: all;

    background-color: var(--white-color);
    box-shadow: rgba(0, 0, 0, 0.07) 0px 2px 4px, rgba(0, 0, 0, 0.13) 0px 2px 6px;
    /* border-top-right-radius: 1rem;
    border-top-left-radius: 1rem; */

    transition: .1s ease-in-out;
}

.chat-minimizer {
    padding: .33rem 1rem;
}

.chat-minimizer {
    display: flex;

    width: 100%;
    height: 2.5rem;
    background-color: var(--accent-color);
    cursor: pointer;

    box-sizing: border-box;

    align-items: center;
    user-select: none;

    font-size: 1.15rem;
    color: var(--white-color);
}

.chat-view {
    height: 80%;
    padding: .5rem 1rem;

    overflow-y: scroll;
}

.chat-minimized {
    transform: translateY(calc(var(--chat-height) - 2.5rem));
}


.chat-msg {
    padding: .4rem .6rem;
    margin-top: .5rem;
    margin-left: 0;
    margin-right: 20%;
    width: 80%;

    box-sizing: border-box;

    align-self: flex-start;

    background-color: var(--dim-color);
    color: var(--black-color);

    border-radius: .3rem;
}

.chat-msg.own {
    margin-left: 20%;
    margin-right: 0;
    width: 80%;

    box-sizing: border-box;

    align-self: flex-end;

    background-color: var(--main-color);
    color: var(--white-color);
}

.chat-loading {
    background: linear-gradient(45deg, var(--dim-color) 0% 40%, var(--white-color) 45% 55%, var(--dim-color) 60% 100%);
    background-size: 200% 200%;
    animation: loading 1.5s linear infinite;
}

.input-box {
    margin-bottom: .5rem;
    padding: 0 .5rem;

    display: flex;
    width: 100%;
    align-items: center;
}

#chat-in {
    padding-left: .5rem;
    width: 80%;
    height: 2rem;

    box-sizing: border-box;

    border: 1px solid var(--accent-color);
    border-bottom-left-radius: .3rem;
    border-top-left-radius: .3rem;
    /* border-top: 2px solid var(--accent-color); */
    /* border-left: 1px solid var(--accent-color); */
}

#chat-in:focus {
    outline: none;
    background-color: var(--dim-color);
}

#chat-send {
    width: 40%;
    height: 2rem;

    margin: 0;
    padding: 0;

    box-sizing: border-box;

    border-radius: 0;
    background-color: var(--accent-color);
    border: 0px;

    font-size: 1rem;
    font-weight: 300;

    cursor: pointer;

    color: var(--white-color);
}
`;


    let style = window.top.document.createElement("style");
    style.innerText = STYLE;
    window.top.document.getElementsByTagName("head")[0].appendChild(style);
    
    let dependencies = window.top.document.createElement("script");
    dependencies.src = "https://cdn.jsdelivr.net/npm/marked/marked.min.js";
    window.top.document.getElementsByTagName("head")[0].appendChild(dependencies);

    /**
     * 
     * @param {Array<Message>} msg
     * @param {onChatStarted} onChatStarted 
     * @param {onChatToken} onChatToken 
     * @param {onChatEnd} onChatEnd 
    */
    async function sendMessage(msg, onChatStarted = () => { }, onChatToken = () => { }, onChatEnd = () => { }) {
        return new Promise((resolve) => {
            let ws = new WebSocket("wss://nanobot.dow99999.dev/askstream");
            let rload = false;

            ws.addEventListener("open", (ev) => {
                ws.send(JSON.stringify({ messages: msg }));
            });

            ws.addEventListener("message", (data) => {
                if (!rload) {
                    rload = true;
                    onChatStarted();
                }
                onChatToken(data.data);
            });
            ws.addEventListener("close", () => {
                onChatEnd();
                resolve(true);
            });
        })
    }

    /**
     * 
     * @param {HTMLElement} container 
    */
    function loadDOMelements(container) {
        let c_c = document.createElement("div");
        c_c.classList.add("chat-container");
        let c_b = document.createElement("div");
        c_b.classList.add("chat-box");
        let c_m = document.createElement("div");
        c_m.classList.add("chat-minimizer");
        c_m.innerText = "Tens cap pregunta?";
        let c_v = document.createElement("div");
        c_v.classList.add("chat-view");
        let i_b = document.createElement("div");
        i_b.classList.add("input-box");
        let c_in = document.createElement("input");
        c_in.id = "chat-in";
        let c_send = document.createElement("button");
        c_send.id = "chat-send";
        c_send.innerText = "Preguntar";

        c_c.appendChild(c_b);
        c_b.appendChild(c_m);
        c_b.appendChild(c_v);
        c_b.appendChild(i_b);
        i_b.appendChild(c_in);
        i_b.appendChild(c_send);

        container.appendChild(c_c);
    }

    /**
     * @typedef {Object} Message
     * @property {"assistant"|"user"} role
     * @property {string} content
    */

    let blocked = false;

    (() => {
        loadDOMelements(window.top.document.getElementsByTagName("body")[0]);

        let btn = window.top.document.getElementById("chat-send");
        let input = window.top.document.getElementById("chat-in");
        let chat_messages = window.top.document.getElementsByClassName("chat-view")[0]
        let minimizer = window.top.document.getElementsByClassName("chat-minimizer")[0];

        async function manageMessage() {
            if (blocked) return;

            let pregunta = input.value.trim();
            if (input.value === "") return;

            blocked = true;

            let chat = window.top.document.createElement("div");
            chat.innerText = pregunta;

            chat.classList.add("chat-msg", "own");

            chat_messages.appendChild(chat);
            input.value = "";

            let loading = window.top.document.createElement("div");
            loading.innerHTML = "<br>";
            loading.classList.add("chat-msg", "chat-loading");
            chat_messages.appendChild(loading);
            chat_messages.scrollTo(0, chat_messages.scrollHeight);

            chat = window.top.document.createElement("div");
            chat.classList.add("chat-msg");

            let response = "";
            await sendMessage(pregunta, () => {
                loading.remove();
                chat_messages.appendChild(chat);
                chat_messages.scrollTo(0, chat_messages.scrollHeight);
            }, (token) => {
                response += token;
                chat.innerHTML = marked.parse(response);
                chat_messages.scrollTo(0, chat_messages.scrollHeight);
            }, () => {
                chat_messages.scrollTo(0, chat_messages.scrollHeight);
            });

            blocked = false;
        }

        minimizer.addEventListener("click", (e) => {
            minimizer.parentElement.classList.toggle("chat-minimized");
        })

        btn.addEventListener("click", manageMessage)

        input.addEventListener("keypress", (e) => {
            if (e.key === "Enter") manageMessage();
        })
    })();
}

document.addEventListener("DOMContentLoaded", () => {
    nanobotMain();
});